# Generated by Django 3.2.5 on 2021-07-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.IntegerField(max_length=1)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
