# Generated by Django 3.2.5 on 2021-07-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umsubjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UmSubjects',
            new_name='Subject',
        ),
    ]
